apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  namespace: "ingress-nginx"
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.2.0
  valuesInline: 
    controller:
      watchIngressWithoutClass: true
      ingressClassResource: 
        default: true
        extraArgs: 
          ingress-class: nginx
          enable-ssl-passthrough: ""
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 600
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: internal
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        enabled: true
        type: LoadBalancer
